# !/bin/bash
# export CUDA_VISIBLE_DEVICES=0,1

train_path=./labeled_data/grpo/train.parquet
test_path=./labeled_data/grpo/test.parquet
model_path=Qwen/Qwen2.5-7B-Instruct

train_files="['$train_path']"
test_files="['$test_path']"

max_prompt_length=640
max_response_length=3456
max_fwd_bwd_length=$((max_prompt_length + max_response_length))
max_fwd_length=$(((max_prompt_length + max_response_length) * 8))

python3 -m verl.trainer.main_ppo \
    data.tokenizer='Qwen/Qwen3-8B-Base' \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=4 \
    data.val_batch_size=4 \
    data.max_prompt_length=$max_prompt_length \
    data.max_response_length=$max_response_length \
    data.truncation='left' \
    data.seed=4123698 \
    actor_rollout_ref.model.path=$model_path \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.strategy='fsdp' \
    actor_rollout_ref.actor.use_torch_compile=True \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=$max_fwd_bwd_length \
    actor_rollout_ref.actor.grad_clip=2.0 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.0002 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.optim.optimizer=AdamW \
    actor_rollout_ref.actor.optim.lr=1.2e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.05 \
    actor_rollout_ref.actor.optim.min_lr_ratio=0.4 \
    actor_rollout_ref.actor.optim.lr_scheduler_type='cosine' \
    actor_rollout_ref.actor.optim.betas=[0.9,0.97] \
    actor_rollout_ref.actor.optim.weight_decay=0.01 \
    actor_rollout_ref.actor.fsdp_config.wrap_policy.min_num_params=100000 \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.checkpoint.save_contents=['model','extra'] \
    actor_rollout_ref.ref.fsdp_config.wrap_policy.min_num_params=100000 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=$max_fwd_length \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.prompt_length=$max_prompt_length \
    actor_rollout_ref.rollout.response_length=$max_response_length \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.75 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.max_num_batched_tokens=327680 \
    actor_rollout_ref.rollout.max_num_seqs=4096 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=$max_fwd_length \
    actor_rollout_ref.rollout.n=1 \
    actor_rollout_ref.rollout.calculate_log_probs=True \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.temperature=1.0 \
    actor_rollout_ref.rollout.val_kwargs.top_p=1.0 \
    algorithm.adv_estimator=grpo \
    custom_reward_function.path='./grpo/custom_reward.py' \
    custom_reward_function.name=my_reward_fn \
    trainer.critic_warmup=0 \
    trainer.project_name='verl' \
    trainer.experiment_name='acne_grpo' \
    trainer.logger=['console','tensorboard'] \
    trainer.log_val_generations=1000 \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=5 \
    trainer.total_epochs=3 $@
